# Generated by Django 5.1.4 on 2026-07-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('tema', models.CharField(max_length=200)),
                ('objetivo', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('promocional', 'Promocional'), ('formativo', 'Formativo')], default='preventivo', max_length=12)),
                ('cofacilitadores', models.JSONField(blank=True, default=list)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('duracion_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual')], default='presencial', max_length=12)),
                ('lugar', models.CharField(blank=True, max_length=200)),
                ('poblacion_objetivo', models.JSONField(blank=True, default=dict)),
                ('estado', models.CharField(choices=[('planificado', 'Planificado'), ('ejecutado', 'Ejecutado'), ('documentado', 'Documentado'), ('cerrado', 'Cerrado')], default='planificado', max_length=12)),
                ('gdrive_folder_id', models.CharField(blank=True, max_length=120)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'taller',
                'verbose_name_plural': 'talleres',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='TallerParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_digitada', models.CharField(blank=True, max_length=13)),
                ('validado', models.BooleanField(default=False)),
                ('asistio', models.BooleanField(default=True)),
                ('origen', models.CharField(choices=[('seleccion_lista', 'Selección de lista'), ('cedula_digitada', 'Cédula digitada')], max_length=16)),
                ('snapshot_academico', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'participante de taller',
                'verbose_name_plural': 'participantes de talleres',
            },
        ),
    ]
