# Generated by Django 5.1.4 on 2026-07-14 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('expediente', '0002_initial'),
        ('talleres', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taller',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taller',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='talleres', to='usuarios.perfilprofesional'),
        ),
        migrations.AddField(
            model_name='taller',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.seccion'),
        ),
        migrations.AddField(
            model_name='taller',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='talleres', to='core.servicio'),
        ),
        migrations.AddField(
            model_name='tallerparticipante',
            name='expediente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talleres', to='expediente.expediente'),
        ),
        migrations.AddField(
            model_name='tallerparticipante',
            name='taller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='talleres.taller'),
        ),
        migrations.AddConstraint(
            model_name='tallerparticipante',
            constraint=models.UniqueConstraint(condition=models.Q(('cedula_digitada__gt', '')), fields=('taller', 'cedula_digitada'), name='uniq_taller_cedula'),
        ),
    ]
