# Generated by Django 5.1.4 on 2026-07-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('dia_semana', models.PositiveSmallIntegerField(help_text='0=lunes … 6=domingo')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('duracion_turno_min', models.PositiveSmallIntegerField(default=20)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'agenda',
                'verbose_name_plural': 'agendas',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(db_index=True)),
                ('estado', models.CharField(choices=[('reservada', 'Reservada'), ('confirmada', 'Confirmada'), ('en_espera', 'En espera'), ('en_atencion', 'En atención'), ('atendida', 'Atendida'), ('no_asistio', 'No asistió'), ('cancelada', 'Cancelada'), ('reprogramada', 'Reprogramada')], default='reservada', max_length=14)),
                ('motivo', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'cita',
                'verbose_name_plural': 'citas',
                'ordering': ['fecha_hora'],
            },
        ),
    ]
