# Generated by Django 6.0.7 on 2026-07-14 21:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_initial'),
        ('core', '0002_initial'),
        ('expediente', '0002_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('motivo', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'bloqueo de agenda',
                'verbose_name_plural': 'bloqueos de agenda',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AlterModelOptions(
            name='agenda',
            options={'ordering': ['profesional', 'dia_semana', 'hora_inicio'], 'verbose_name': 'agenda', 'verbose_name_plural': 'agendas'},
        ),
        migrations.AddField(
            model_name='agenda',
            name='vigente_desde',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='agenda',
            name='vigente_hasta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='atendida_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='cita_origen',
            field=models.ForeignKey(blank=True, help_text='Si esta cita reemplaza a otra reprogramada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reprogramaciones', to='citas.cita'),
        ),
        migrations.AddField(
            model_name='cita',
            name='duracion_min',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='cita',
            name='llegada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='origen',
            field=models.CharField(choices=[('ventanilla', 'Ventanilla'), ('autogestion', 'Autogestión (paciente)'), ('derivacion', 'Derivación interna'), ('emergencia', 'Emergencia')], default='ventanilla', max_length=12),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='dia_semana',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')]),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendas', to='core.servicio'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='core.servicio'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['servicio', 'fecha_hora'], name='citas_cita_servici_f7644e_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['profesional', 'fecha_hora'], name='citas_cita_profesi_f51918_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['expediente', 'fecha_hora'], name='citas_cita_expedie_1ef640_idx'),
        ),
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['reservada', 'confirmada', 'en_espera', 'en_atencion'])), fields=('profesional', 'fecha_hora'), name='uniq_cita_activa_profesional_hora'),
        ),
        migrations.AddField(
            model_name='bloqueoagenda',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloqueoagenda',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloqueoagenda',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='usuarios.perfilprofesional'),
        ),
    ]
