# Generated by Django 5.1.4 on 2026-09-02 13:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citas", "0003_bloqueoagenda_alter_agenda_options_and_more"),
        ("core", "0002_initial"),
        ("expediente", "0003_expediente_ck_expediente_discapacidad_hasta_100"),
        ("usuarios", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="agenda",
            constraint=models.CheckConstraint(
                condition=models.Q(("hora_inicio__lt", models.F("hora_fin"))),
                name="ck_agenda_inicio_antes_de_fin",
            ),
        ),
        migrations.AddConstraint(
            model_name="agenda",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("vigente_hasta__isnull", True),
                    ("vigente_hasta__gte", models.F("vigente_desde")),
                    _connector="OR",
                ),
                name="ck_agenda_vigencia_coherente",
            ),
        ),
        migrations.AddConstraint(
            model_name="bloqueoagenda",
            constraint=models.CheckConstraint(
                condition=models.Q(("fecha_inicio__lt", models.F("fecha_fin"))),
                name="ck_bloqueo_inicio_antes_de_fin",
            ),
        ),
        migrations.AddConstraint(
            model_name="cita",
            constraint=models.CheckConstraint(
                condition=models.Q(("duracion_min__gt", 0)),
                name="ck_cita_duracion_positiva",
            ),
        ),
    ]
