# Generated by Django 5.1.4 on 2026-07-14 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('expediente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtencionMedicina',
            fields=[
                ('atencion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='medicina', serialize=False, to='expediente.atencion')),
                ('enfermedad_actual', models.TextField(blank=True)),
                ('revision_sistemas', models.JSONField(blank=True, default=dict)),
                ('examen_fisico', models.JSONField(blank=True, default=dict)),
                ('plan_tratamiento', models.TextField(blank=True)),
                ('indicaciones', models.TextField(blank=True)),
                ('dias_reposo', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'atención de medicina',
                'verbose_name_plural': 'atenciones de medicina',
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('presuntivo', 'Presuntivo'), ('definitivo', 'Definitivo')], default='presuntivo', max_length=12)),
                ('principal', models.BooleanField(default=True)),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='expediente.atencion')),
                ('cie10', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cie10')),
            ],
            options={
                'verbose_name': 'diagnóstico',
                'verbose_name_plural': 'diagnósticos',
            },
        ),
    ]
