# Generated by Django 5.1.4 on 2026-07-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
        ("expediente", "0002_initial"),
        ("medicina", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="atencionmedicina",
            name="observaciones",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="atencionmedicina",
            name="proxima_cita_sugerida",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="diagnostico",
            name="condicion",
            field=models.CharField(
                choices=[("primera", "Primera vez"), ("subsecuente", "Subsecuente")],
                default="primera",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="diagnostico",
            name="observacion",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="atencionmedicina",
            name="enfermedad_actual",
            field=models.TextField(
                blank=True, help_text="Cronología del padecimiento actual."
            ),
        ),
        migrations.AlterField(
            model_name="atencionmedicina",
            name="examen_fisico",
            field=models.JSONField(
                blank=True, default=dict, help_text="{region/sistema: hallazgos}"
            ),
        ),
        migrations.AlterField(
            model_name="atencionmedicina",
            name="revision_sistemas",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="{sistema: hallazgos}, ej: {'cardio': 'palpitaciones ocasionales'}",
            ),
        ),
        migrations.AlterField(
            model_name="diagnostico",
            name="principal",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="diagnostico",
            index=models.Index(
                fields=["atencion", "principal"], name="medicina_di_atencio_5e2d67_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="diagnostico",
            constraint=models.UniqueConstraint(
                fields=("atencion", "cie10"), name="uniq_atencion_cie10"
            ),
        ),
    ]
