# Generated by Django 5.1.4 on 2026-07-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrarreferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recepcion', models.DateField()),
                ('hallazgos', models.TextField(blank=True)),
                ('tratamiento_instaurado', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Derivacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.CharField(max_length=255)),
                ('resumen', models.TextField(blank=True)),
                ('prioridad', models.CharField(choices=[('normal', 'Normal'), ('urgente', 'Urgente')], default='normal', max_length=10)),
                ('estado', models.CharField(choices=[('enviada', 'Enviada'), ('aceptada', 'Aceptada'), ('agendada', 'Agendada'), ('atendida', 'Atendida'), ('retornada', 'Retornada'), ('rechazada', 'Rechazada')], default='enviada', max_length=10)),
                ('retorno_texto', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'derivación',
                'verbose_name_plural': 'derivaciones',
            },
        ),
        migrations.CreateModel(
            name='ReferenciaExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('institucion_destino', models.CharField(max_length=200)),
                ('especialidad', models.CharField(blank=True, max_length=120)),
                ('motivo', models.CharField(max_length=255)),
                ('resumen_clinico', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'referencia externa',
                'verbose_name_plural': 'referencias externas',
            },
        ),
    ]
