# Generated by Django 5.1.4 on 2026-07-14 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('derivaciones', '0001_initial'),
        ('expediente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='derivacion',
            name='atencion_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivaciones_atendidas', to='expediente.atencion'),
        ),
        migrations.AddField(
            model_name='derivacion',
            name='atencion_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derivaciones_emitidas', to='expediente.atencion'),
        ),
    ]
