# Generated by Django 5.1.4 on 2026-07-14 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('derivaciones', '0002_initial'),
        ('expediente', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='derivacion',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='derivacion',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='derivacion',
            name='servicio_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derivaciones_recibidas', to='core.servicio'),
        ),
        migrations.AddField(
            model_name='referenciaexterna',
            name='atencion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referencias', to='expediente.atencion'),
        ),
        migrations.AddField(
            model_name='referenciaexterna',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referenciaexterna',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contrarreferencia',
            name='referencia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrarreferencia', to='derivaciones.referenciaexterna'),
        ),
    ]
