# Generated by Django 5.1.4 on 2026-07-14 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expediente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaPsicopedagogica',
            fields=[
                ('atencion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='psicopedagogia', serialize=False, to='expediente.atencion')),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('historial_academico', models.JSONField(blank=True, default=dict)),
                ('estilos_aprendizaje', models.JSONField(blank=True, default=dict)),
                ('plan_intervencion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'ficha psicopedagógica',
                'verbose_name_plural': 'fichas psicopedagógicas',
            },
        ),
        migrations.CreateModel(
            name='SeguimientoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=20)),
                ('promedio_antes', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('promedio_despues', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='psicopedagogia.fichapsicopedagogica')),
            ],
        ),
    ]
