# Generated by Django 5.1.4 on 2026-07-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('tipo', models.CharField(max_length=60)),
                ('titulo', models.CharField(max_length=150)),
                ('mensaje', models.TextField()),
                ('canal', models.CharField(choices=[('in_app', 'En la aplicación'), ('email', 'Correo'), ('sms', 'SMS')], default='in_app', max_length=8)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('leida', 'Leída'), ('fallida', 'Fallida')], default='pendiente', max_length=10)),
                ('referencia_tipo', models.CharField(blank=True, max_length=40)),
                ('referencia_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('programada_para', models.DateTimeField(blank=True, null=True)),
                ('enviada_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'notificación',
                'verbose_name_plural': 'notificaciones',
                'ordering': ['-creado_en'],
            },
        ),
    ]
