# Generated by Django 5.1.4 on 2026-09-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notificaciones", "0003_notificacion_destinatario_correo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificacion",
            name="leida_en",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
