# Generated by Django 5.1.4 on 2026-07-14 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expediente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('perfil', models.CharField(blank=True, max_length=80)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'examen',
                'verbose_name_plural': 'catálogo de exámenes',
            },
        ),
        migrations.CreateModel(
            name='ResultadoParametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametro', models.CharField(max_length=120)),
                ('valor', models.CharField(max_length=60)),
                ('unidad', models.CharField(blank=True, max_length=30)),
                ('ref_min', models.CharField(blank=True, max_length=30)),
                ('ref_max', models.CharField(blank=True, max_length=30)),
                ('marcador', models.CharField(choices=[('normal', 'Normal'), ('alto', 'Alto'), ('bajo', 'Bajo'), ('critico', 'Crítico')], default='normal', max_length=10)),
                ('validado_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'resultado de parámetro',
                'verbose_name_plural': 'resultados de parámetros',
            },
        ),
        migrations.CreateModel(
            name='OrdenExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laboratorio.examen')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('prioridad', models.CharField(choices=[('rutina', 'Rutina'), ('urgente', 'Urgente')], default='rutina', max_length=10)),
                ('diagnostico_presuntivo', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('creada', 'Creada'), ('muestra_tomada', 'Muestra tomada'), ('en_proceso', 'En proceso'), ('resultado', 'Resultado registrado'), ('validado', 'Validado'), ('publicado', 'Publicado'), ('anulada', 'Anulada'), ('rechazada', 'Muestra rechazada')], default='creada', max_length=16)),
                ('enviado_correo_paciente', models.BooleanField(default=False)),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_lab', to='expediente.atencion')),
            ],
            options={
                'verbose_name': 'orden de laboratorio',
                'verbose_name_plural': 'órdenes de laboratorio',
            },
        ),
    ]
