# Generated by Django 5.1.4 on 2026-07-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0003_parametroexamen_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ordenlaboratorio',
            new_name='laboratorio_estado_a424b7_idx',
            old_name='laboratori_estado_a1b2c3_idx',
        ),
        migrations.AddField(
            model_name='ordenlaboratorio',
            name='fecha_toma_muestra',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenlaboratorio',
            name='motivo_rechazo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='examen',
            name='perfil',
            field=models.CharField(blank=True, help_text='Hematología, Química sanguínea, etc.', max_length=80),
        ),
    ]
