# Generated by Django 5.1.4 on 2026-09-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "laboratorio",
            "0004_rename_laboratori_estado_a1b2c3_idx_laboratorio_estado_a424b7_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="parametroexamen",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ref_min__isnull", True),
                    ("ref_max__isnull", True),
                    ("ref_min__lte", models.F("ref_max")),
                    _connector="OR",
                ),
                name="ck_parametro_referencia_coherente",
            ),
        ),
        migrations.AddConstraint(
            model_name="parametroexamen",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("critico_min__isnull", True),
                    ("critico_max__isnull", True),
                    ("critico_min__lte", models.F("critico_max")),
                    _connector="OR",
                ),
                name="ck_parametro_critico_coherente",
            ),
        ),
        migrations.AddConstraint(
            model_name="parametroexamen",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("edad_min__isnull", True),
                    ("edad_max__isnull", True),
                    ("edad_min__lte", models.F("edad_max")),
                    _connector="OR",
                ),
                name="ck_parametro_edad_coherente",
            ),
        ),
    ]
