# Generated by Django 5.1.4 on 2026-07-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirmaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_ref_tipo', models.CharField(help_text='Modelo firmado (p. ej. atencion, receta).', max_length=40)),
                ('documento_ref_id', models.PositiveBigIntegerField()),
                ('tipo_firma', models.CharField(choices=[('electronica', 'Electrónica simple'), ('digital_certificado', 'Digital con certificado')], max_length=20)),
                ('hash_documento', models.CharField(max_length=64)),
                ('sello_tiempo', models.DateTimeField(auto_now_add=True)),
                ('certificado_serial', models.CharField(blank=True, max_length=120)),
                ('valida', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'firma de documento',
                'verbose_name_plural': 'firmas de documentos',
            },
        ),
    ]
