# Generated by Django 5.1.4 on 2026-07-14 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firma', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='firmadocumento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='firmas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='firmadocumento',
            index=models.Index(fields=['documento_ref_tipo', 'documento_ref_id'], name='firma_firma_documen_01630f_idx'),
        ),
    ]
