# Generated by Django 5.1.4 on 2026-07-17 15:52

import apps.firma.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0002_initial'),
        ('firma', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='firmadocumento',
            name='entidad_certificadora',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='firmadocumento',
            name='fecha_firma',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firmadocumento',
            name='firmante_cedula',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AddField(
            model_name='firmadocumento',
            name='firmante_nombre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='SolicitudFirma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('correlacion', models.CharField(default=apps.firma.models._nueva_correlacion, editable=False, max_length=64, unique=True)),
                ('documento_ref_tipo', models.CharField(max_length=40)),
                ('documento_ref_id', models.PositiveBigIntegerField()),
                ('tipo_documento', models.CharField(default='informe', max_length=60)),
                ('cedula_solicitante', models.CharField(max_length=13)),
                ('nombre_documento', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('preparada', 'PDF generado, sin token'), ('enviada', 'Token obtenido, esperando al firmador'), ('firmada', 'Documento firmado y almacenado'), ('fallida', 'Rechazada o con error'), ('expirada', 'El token caducó sin firmarse')], default='preparada', max_length=10)),
                ('pdf_original', models.BinaryField()),
                ('hash_original', models.CharField(max_length=64)),
                ('pdf_firmado', models.BinaryField(blank=True, null=True)),
                ('hash_firmado', models.CharField(blank=True, max_length=64)),
                ('token_expira_en', models.DateTimeField(blank=True, null=True)),
                ('razon', models.CharField(blank=True, max_length=70)),
                ('certificado', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True)),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_firma', to='expediente.atencion')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_firma', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'solicitud de firma',
                'verbose_name_plural': 'solicitudes de firma',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='firmadocumento',
            name='solicitud',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firma', to='firma.solicitudfirma'),
        ),
        migrations.AddIndex(
            model_name='solicitudfirma',
            index=models.Index(fields=['documento_ref_tipo', 'documento_ref_id'], name='firma_solic_documen_56c2b5_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudfirma',
            index=models.Index(fields=['estado'], name='firma_solic_estado_777c41_idx'),
        ),
    ]
