# Generated by Django 5.1.4 on 2026-07-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargaInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('hash_archivo', models.CharField(help_text='SHA-256 del archivo cargado.', max_length=64)),
                ('formato', models.CharField(choices=[('xlsx', 'xlsx'), ('csv', 'csv')], max_length=8)),
                ('total_filas', models.PositiveIntegerField(default=0)),
                ('altas', models.PositiveIntegerField(default=0)),
                ('actualizaciones', models.PositiveIntegerField(default=0)),
                ('errores', models.PositiveIntegerField(default=0)),
                ('mapeo_columnas', models.JSONField(blank=True, default=dict)),
                ('bitacora', models.JSONField(blank=True, default=dict)),
                ('estado', models.CharField(choices=[('subida', 'Subida'), ('mapeada', 'Mapeada'), ('validada', 'Validada'), ('aplicada', 'Aplicada'), ('rechazada', 'Rechazada')], default='subida', max_length=12)),
            ],
            options={
                'verbose_name': 'carga institucional',
                'verbose_name_plural': 'cargas institucionales',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='DatoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultad', models.CharField(blank=True, max_length=150)),
                ('carrera', models.CharField(blank=True, max_length=150)),
                ('nivel', models.CharField(blank=True, max_length=50)),
                ('modalidad', models.CharField(blank=True, max_length=50)),
                ('ciclo', models.CharField(blank=True, max_length=50)),
                ('oferta_academica', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=50)),
                ('paralelo', models.CharField(blank=True, max_length=20)),
                ('jornada', models.CharField(blank=True, max_length=50)),
                ('email_institucional', models.EmailField(blank=True, max_length=254)),
                ('ficha_raw', models.JSONField(default=dict, help_text='Fila original completa de la ficha.')),
                ('cargado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'dato académico',
                'verbose_name_plural': 'datos académicos',
            },
        ),
    ]
