# Generated by Django 5.1.4 on 2026-07-14 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('core', '0001_initial'),
        ('expediente', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cargainstitucional',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cargainstitucional',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cargainstitucional',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargas', to='core.periodoacademico'),
        ),
        migrations.AddField(
            model_name='datoacademico',
            name='carga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.cargainstitucional'),
        ),
        migrations.AddField(
            model_name='datoacademico',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.periodoacademico'),
        ),
        migrations.AddField(
            model_name='datoacademico',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos_academicos', to='expediente.persona'),
        ),
        migrations.AddIndex(
            model_name='datoacademico',
            index=models.Index(fields=['facultad', 'carrera'], name='academico_d_faculta_281759_idx'),
        ),
        migrations.AddConstraint(
            model_name='datoacademico',
            constraint=models.UniqueConstraint(fields=('persona', 'periodo'), name='uniq_persona_periodo'),
        ),
    ]
