# Generated by Django 5.1.4 on 2026-09-06 20:35

import apps.academico.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academico", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargainstitucional",
            name="estamento",
            field=models.CharField(
                choices=apps.academico.models.estamentos_choices,
                default="estudiante",
                max_length=20,
            ),
        ),
    ]
