# Generated by Django 5.1.4 on 2026-07-19 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expediente', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VinculacionPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verificado', models.BooleanField(default=False)),
                ('correo_destino', models.EmailField(help_text='Correo institucional al que se envió la verificación.', max_length=254)),
                ('token_hash', models.CharField(editable=False, max_length=64)),
                ('token_expira_en', models.DateTimeField()),
                ('verificado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expediente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vinculacion_portal', to='expediente.expediente')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vinculacion_portal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vinculación del portal',
                'verbose_name_plural': 'vinculaciones del portal',
            },
        ),
    ]
