# Generated by Django 5.1.4 on 2026-07-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('alergia', 'Alergia'), ('riesgo', 'Riesgo clínico'), ('social', 'Alerta social'), ('nee', 'Necesidad educativa especial')], max_length=12)),
                ('descripcion', models.CharField(max_length=255)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'alerta clínica',
                'verbose_name_plural': 'alertas clínicas',
            },
        ),
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(db_index=True)),
                ('tipo', models.CharField(choices=[('primera', 'Primera'), ('subsecuente', 'Subsecuente')], default='primera', max_length=12)),
                ('origen', models.CharField(choices=[('cita', 'Cita'), ('espontanea', 'Demanda espontánea'), ('derivacion', 'Derivación'), ('emergencia', 'Emergencia')], default='cita', max_length=12)),
                ('motivo_consulta', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('cerrada', 'Cerrada'), ('firmada', 'Firmada'), ('enmendada', 'Enmendada')], default='borrador', max_length=12)),
                ('snapshot_academico', models.JSONField(blank=True, default=dict)),
                ('firmada_en', models.DateTimeField(blank=True, null=True)),
                ('hash_firma', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'verbose_name': 'atención',
                'verbose_name_plural': 'atenciones',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Consentimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('tipo', models.CharField(max_length=80)),
                ('texto_version', models.CharField(max_length=20)),
                ('otorgado', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'consentimiento',
                'verbose_name_plural': 'consentimientos',
            },
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('numero_expediente', models.CharField(db_index=True, max_length=20, unique=True)),
                ('grupo_sanguineo', models.CharField(blank=True, max_length=5)),
                ('discapacidad_tipo', models.CharField(blank=True, max_length=60)),
                ('discapacidad_porcentaje', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fecha_apertura', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'expediente',
                'verbose_name_plural': 'expedientes',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('cedula', models.CharField(db_index=True, max_length=13, unique=True)),
                ('tipo_documento', models.CharField(default='cedula', max_length=20)),
                ('nombres', models.CharField(max_length=120)),
                ('apellidos', models.CharField(max_length=120)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=20)),
                ('genero', models.CharField(blank=True, max_length=30)),
                ('tipo_vinculo', models.CharField(choices=[('estudiante', 'Estudiante'), ('docente', 'Docente'), ('administrativo', 'Administrativo'), ('trabajador', 'Trabajador'), ('externo', 'Externo/Particular')], max_length=20)),
                ('correo_institucional', models.EmailField(blank=True, max_length=254)),
                ('correo_personal', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('celular', models.CharField(blank=True, max_length=20)),
                ('procedencia', models.JSONField(blank=True, default=dict)),
                ('residencia_actual', models.JSONField(blank=True, default=dict)),
                ('contacto_referencia', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'persona',
                'verbose_name_plural': 'personas',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
    ]
