# Generated by Django 5.1.4 on 2026-09-02 13:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expediente", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="expediente",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("discapacidad_porcentaje__isnull", True),
                    ("discapacidad_porcentaje__lte", 100),
                    _connector="OR",
                ),
                name="ck_expediente_discapacidad_hasta_100",
            ),
        ),
    ]
