# Generated by Django 5.1.4 on 2026-09-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expediente", "0003_expediente_ck_expediente_discapacidad_hasta_100"),
    ]

    operations = [
        migrations.AddField(
            model_name="persona",
            name="etnia",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name="alertaclinica",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("alergia", "Alergia"),
                    ("riesgo", "Riesgo clínico"),
                    ("social", "Alerta social"),
                    ("nee", "Necesidad educativa especial"),
                    ("gestacion", "Gestación"),
                    ("lactancia", "Lactancia"),
                    ("enf_catastrofica", "Enfermedad catastrófica"),
                ],
                max_length=20,
            ),
        ),
    ]
