# Generated by Django 5.1.4 on 2026-09-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expediente", "0004_etnia_y_tipos_alerta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="persona",
            name="etnia",
        ),
        migrations.AddField(
            model_name="persona",
            name="identidad_orientacion_sexual",
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
