# Generated by Django 5.1.4 on 2026-09-04 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
        ("expediente", "0005_identidad_orientacion_sexual"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AjusteDeServicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("eliminado_en", models.DateTimeField(blank=True, null=True)),
                (
                    "variable",
                    models.CharField(
                        choices=[
                            ("sexo", "Sexo"),
                            ("grupo_sanguineo", "Grupo sanguíneo"),
                            ("discapacidad_tipo", "Tipo de discapacidad"),
                            ("discapacidad_porcentaje", "Porcentaje de discapacidad"),
                            ("gestacion", "Embarazo"),
                            ("lactancia", "Lactancia"),
                            ("enf_catastrofica", "Enfermedad catastrófica"),
                            ("nee", "Necesidad educativa especial"),
                        ],
                        max_length=30,
                    ),
                ),
                ("valor", models.CharField(max_length=120)),
                ("nota", models.CharField(blank=True, max_length=255)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "eliminado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expediente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ajustes",
                        to="expediente.expediente",
                    ),
                ),
                (
                    "servicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ajustes",
                        to="core.servicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "ajuste de servicio",
                "verbose_name_plural": "ajustes de servicio",
                "ordering": ["variable"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("expediente", "servicio", "variable"),
                        name="uniq_ajuste_por_servicio_y_variable",
                    )
                ],
            },
        ),
    ]
