# Generated by Django 5.1.4 on 2026-09-08 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expediente", "0006_ajuste_de_servicio"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertaclinica",
            name="origen",
            field=models.CharField(
                choices=[
                    ("matricula", "Declarada en matrícula"),
                    ("profesional", "Registrada por un profesional"),
                ],
                default="matricula",
                max_length=12,
            ),
        ),
    ]
