# Generated by Django 5.1.4 on 2026-07-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BecaBeneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('monto_o_porcentaje', models.CharField(blank=True, max_length=60)),
                ('resolucion', models.CharField(blank=True, max_length=120)),
                ('datos_bancarios_cifrados', models.JSONField(blank=True, default=dict)),
                ('origen', models.CharField(choices=[('manual', 'Registro manual'), ('carga_masiva', 'Carga masiva'), ('api_externa', 'API sistema de becas')], default='manual', max_length=14)),
                ('id_externo', models.CharField(blank=True, help_text='Clave en el sistema de becas institucional (fase 2).', max_length=60)),
                ('estado', models.CharField(choices=[('registrado', 'Registrado'), ('en_seguimiento', 'En seguimiento'), ('suspendido', 'Suspendido'), ('terminado', 'Terminado')], default='registrado', max_length=16)),
                ('causal', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'beneficiario de beca',
                'verbose_name_plural': 'beneficiarios de becas',
            },
        ),
        migrations.CreateModel(
            name='SeguimientoBeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('entrevista', 'Entrevista'), ('verificacion_matricula', 'Verificación de matrícula'), ('novedad', 'Novedad'), ('informe_social', 'Informe social')], max_length=24)),
                ('detalle', models.TextField(blank=True)),
                ('matricula_vigente', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'seguimiento de beca',
                'verbose_name_plural': 'seguimientos de becas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='TipoBeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.SlugField(max_length=30, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'tipo de beca',
                'verbose_name_plural': 'tipos de beca',
            },
        ),
    ]
