# Generated by Django 5.1.4 on 2026-07-14 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('becas', '0001_initial'),
        ('core', '0001_initial'),
        ('expediente', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='becabeneficiario',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='becabeneficiario',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='becabeneficiario',
            name='expediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='becas', to='expediente.expediente'),
        ),
        migrations.AddField(
            model_name='becabeneficiario',
            name='periodo_desde',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='becas_desde', to='core.periodoacademico'),
        ),
        migrations.AddField(
            model_name='becabeneficiario',
            name='periodo_hasta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='becas_hasta', to='core.periodoacademico'),
        ),
        migrations.AddField(
            model_name='seguimientobeca',
            name='beneficiario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='becas.becabeneficiario'),
        ),
        migrations.AddField(
            model_name='seguimientobeca',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.periodoacademico'),
        ),
        migrations.AddField(
            model_name='seguimientobeca',
            name='registrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.perfilprofesional'),
        ),
        migrations.AddField(
            model_name='becabeneficiario',
            name='tipo_beca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='becas.tipobeca'),
        ),
    ]
