# Generated by Django 5.1.4 on 2026-07-14 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expediente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaPsicologica',
            fields=[
                ('atencion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='psicologia', serialize=False, to='expediente.atencion')),
                ('motivo', models.TextField(blank=True)),
                ('historia_problema', models.TextField(blank=True)),
                ('estado_mental', models.JSONField(blank=True, default=dict)),
                ('impresion_diagnostica', models.CharField(blank=True, max_length=255)),
                ('plan_terapeutico', models.TextField(blank=True)),
                ('riesgo_nivel', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], default='bajo', help_text='Riesgo alto dispara protocolo de alerta al coordinador.', max_length=10)),
            ],
            options={
                'verbose_name': 'ficha psicológica',
                'verbose_name_plural': 'fichas psicológicas',
            },
        ),
        migrations.CreateModel(
            name='AplicacionEscala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escala', models.CharField(max_length=120)),
                ('puntaje', models.CharField(blank=True, max_length=40)),
                ('interpretacion', models.CharField(blank=True, max_length=255)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='psicologia.fichapsicologica')),
            ],
        ),
        migrations.CreateModel(
            name='SesionPsicologica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('fecha', models.DateField()),
                ('temas', models.TextField(blank=True)),
                ('tecnicas', models.CharField(blank=True, max_length=255)),
                ('evolucion', models.TextField(blank=True)),
                ('proxima_sesion', models.DateField(blank=True, null=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='psicologia.fichapsicologica')),
            ],
            options={
                'verbose_name': 'sesión psicológica',
                'verbose_name_plural': 'sesiones psicológicas',
                'ordering': ['numero'],
            },
        ),
    ]
