# Generated by Django 5.1.4 on 2026-07-16 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicologia', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalaPsicometrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('puntaje_min', models.PositiveSmallIntegerField(default=0)),
                ('puntaje_max', models.PositiveSmallIntegerField()),
                ('tramos', models.JSONField(blank=True, default=list, help_text='[{min, max, etiqueta, alerta}]')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'escala psicométrica',
                'verbose_name_plural': 'escalas psicométricas',
                'ordering': ['codigo'],
            },
        ),
        migrations.AlterModelOptions(
            name='aplicacionescala',
            options={'ordering': ['-fecha'], 'verbose_name': 'aplicación de escala', 'verbose_name_plural': 'aplicaciones de escalas'},
        ),
        migrations.AddField(
            model_name='aplicacionescala',
            name='alerta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fichapsicologica',
            name='estado_proceso',
            field=models.CharField(choices=[('activo', 'Proceso activo'), ('alta', 'Alta'), ('abandono', 'Abandono'), ('derivado', 'Derivado a externo')], default='activo', max_length=10),
        ),
        migrations.AddField(
            model_name='fichapsicologica',
            name='modalidad',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual')], default='presencial', max_length=12),
        ),
        migrations.AddField(
            model_name='fichapsicologica',
            name='nota_riesgo',
            field=models.TextField(blank=True, help_text='Sustento clínico del riesgo. No sale del servicio.'),
        ),
        migrations.AddField(
            model_name='sesionpsicologica',
            name='profesional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_psico', to='usuarios.perfilprofesional'),
        ),
        migrations.AddField(
            model_name='sesionpsicologica',
            name='tareas',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aplicacionescala',
            name='escala',
            field=models.CharField(help_text='Nombre de la escala aplicada', max_length=120),
        ),
        migrations.AlterField(
            model_name='aplicacionescala',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aplicacionescala',
            name='interpretacion',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='fichapsicologica',
            name='estado_mental',
            field=models.JSONField(blank=True, default=dict, help_text='Examen mental: {area: hallazgo}'),
        ),
        migrations.AlterField(
            model_name='fichapsicologica',
            name='riesgo_nivel',
            field=models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], default='bajo', help_text='Riesgo alto dispara protocolo de alerta al coordinador (sin contenido).', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='sesionpsicologica',
            constraint=models.UniqueConstraint(fields=('ficha', 'numero'), name='uniq_sesion_por_ficha'),
        ),
        migrations.AddField(
            model_name='escalapsicometrica',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escalapsicometrica',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aplicacionescala',
            name='escala_catalogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones', to='psicologia.escalapsicometrica'),
        ),
    ]
