# Generated by Django 5.1.4 on 2026-09-03 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilprofesional",
            name="denominacion_cargo",
            field=models.CharField(
                blank=True,
                help_text="Denominación del cargo según el manual de puestos.",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="fecha_nacimiento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ActividadEsencial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orden", models.PositiveSmallIntegerField()),
                ("descripcion", models.CharField(max_length=500)),
                (
                    "actividad_superior",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subactividades",
                        to="usuarios.actividadesencial",
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actividades_esenciales",
                        to="usuarios.perfilprofesional",
                    ),
                ),
            ],
            options={
                "verbose_name": "actividad esencial",
                "verbose_name_plural": "actividades esenciales",
                "ordering": ["orden"],
            },
        ),
    ]
