# Generated by Django 5.1.4 on 2026-09-08 03:28

import apps.usuarios.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_ficha_profesional_ampliada"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="usuario",
            managers=[
                ("objects", apps.usuarios.models.GestorDeUsuarios()),
            ],
        ),
    ]
