# Generated by Django 5.1.4 on 2026-10-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_gestor_con_rol_de_administrador"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="debe_cambiar_clave",
            field=models.BooleanField(
                default=False,
                help_text="La cuenta tiene una clave temporal y no puede usarse hasta cambiarla.",
                verbose_name="debe cambiar la clave",
            ),
        ),
    ]
