# Generated by Django 5.1.4 on 2026-07-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('modulo', models.CharField(max_length=40)),
                ('tipo_documento', models.CharField(max_length=60)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('almacenamiento', models.CharField(choices=[('local', 'Almacén local cifrado'), ('gdrive', 'Google Drive institucional')], default='local', max_length=8)),
                ('ruta_cifrada', models.CharField(blank=True, max_length=500)),
                ('gdrive_file_id', models.CharField(blank=True, max_length=120)),
                ('gdrive_url', models.URLField(blank=True)),
                ('mime', models.CharField(blank=True, max_length=100)),
                ('tamano', models.PositiveIntegerField(default=0)),
                ('hash_sha256', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'verbose_name': 'documento anexo',
                'verbose_name_plural': 'documentos anexos',
            },
        ),
    ]
