# Generated by Django 5.1.4 on 2026-07-14 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0001_initial'),
        ('expediente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoanexo',
            name='atencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='expediente.atencion'),
        ),
    ]
