# Generated by Django 5.1.4 on 2026-07-14 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=150)),
                ('periodicidad', models.CharField(choices=[('mensual', 'Mensual'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('a_demanda', 'A demanda')], max_length=12)),
                ('parametros', models.JSONField(blank=True, default=dict)),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('archivo_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentos.documentoanexo')),
            ],
            options={
                'verbose_name': 'reporte generado',
                'verbose_name_plural': 'reportes generados',
                'ordering': ['-generado_en'],
            },
        ),
    ]
