# Generated by Django 5.1.4 on 2026-07-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispensacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_despachada', models.PositiveIntegerField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'dispensación',
                'verbose_name_plural': 'dispensaciones',
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=60)),
                ('fecha_caducidad', models.DateField(db_index=True)),
                ('cantidad_actual', models.IntegerField(default=0)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('proveedor', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'lote',
                'verbose_name_plural': 'lotes',
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('dci', models.CharField(max_length=150, verbose_name='denominación común internacional')),
                ('nombre_comercial', models.CharField(blank=True, max_length=150)),
                ('concentracion', models.CharField(blank=True, max_length=60)),
                ('forma_farmaceutica', models.CharField(blank=True, max_length=60)),
                ('unidad_medida', models.CharField(blank=True, max_length=30)),
                ('stock_minimo', models.PositiveIntegerField(default=0)),
                ('stock_maximo', models.PositiveIntegerField(default=0)),
                ('requiere_receta', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'medicamento',
                'verbose_name_plural': 'medicamentos',
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso'), ('ajuste_mas', 'Ajuste (+)'), ('ajuste_menos', 'Ajuste (-)'), ('baja', 'Baja'), ('transferencia', 'Transferencia')], max_length=14)),
                ('cantidad', models.IntegerField()),
                ('saldo_resultante', models.IntegerField()),
                ('referencia_doc', models.CharField(blank=True, max_length=60)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'movimiento de inventario',
                'verbose_name_plural': 'movimientos de inventario',
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('valida_hasta', models.DateTimeField()),
                ('estado', models.CharField(choices=[('emitida', 'Emitida'), ('despachada_parcial', 'Despachada parcial'), ('despachada', 'Despachada'), ('caducada', 'Caducada'), ('anulada', 'Anulada')], default='emitida', max_length=20)),
            ],
            options={
                'verbose_name': 'receta',
                'verbose_name_plural': 'recetas',
            },
        ),
        migrations.CreateModel(
            name='RecetaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_prescrita', models.PositiveIntegerField()),
                ('dosis', models.CharField(blank=True, max_length=120)),
                ('via', models.CharField(blank=True, max_length=40)),
                ('frecuencia', models.CharField(blank=True, max_length=60)),
                ('duracion', models.CharField(blank=True, max_length=60)),
                ('indicaciones', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
