# Generated by Django 5.1.4 on 2026-07-14 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expediente', '0002_initial'),
        ('farmacia', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensacion',
            name='despachado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.perfilprofesional'),
        ),
        migrations.AddField(
            model_name='dispensacion',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmacia.lote'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lote',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='farmacia.medicamento'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='farmacia.lote'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.perfilprofesional'),
        ),
        migrations.AddField(
            model_name='receta',
            name='atencion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recetas', to='expediente.atencion'),
        ),
        migrations.AddField(
            model_name='receta',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receta',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recetadetalle',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmacia.medicamento'),
        ),
        migrations.AddField(
            model_name='recetadetalle',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='farmacia.receta'),
        ),
        migrations.AddField(
            model_name='dispensacion',
            name='receta_detalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispensaciones', to='farmacia.recetadetalle'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['medicamento', 'fecha_caducidad'], name='farmacia_lo_medicam_02c869_idx'),
        ),
    ]
