# Generated by Django 5.1.4 on 2026-09-02 13:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmacia", "0002_initial"),
        ("usuarios", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="dispensacion",
            constraint=models.CheckConstraint(
                condition=models.Q(("cantidad_despachada__gt", 0)),
                name="ck_dispensacion_cantidad_positiva",
            ),
        ),
        migrations.AddConstraint(
            model_name="lote",
            constraint=models.UniqueConstraint(
                fields=("medicamento", "numero_lote"), name="uniq_lote_por_medicamento"
            ),
        ),
        migrations.AddConstraint(
            model_name="lote",
            constraint=models.CheckConstraint(
                condition=models.Q(("cantidad_actual__gte", 0)),
                name="ck_lote_cantidad_no_negativa",
            ),
        ),
        migrations.AddConstraint(
            model_name="medicamento",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("stock_maximo", 0),
                    ("stock_maximo__gte", models.F("stock_minimo")),
                    _connector="OR",
                ),
                name="ck_medicamento_min_no_supera_max",
            ),
        ),
        migrations.AddConstraint(
            model_name="recetadetalle",
            constraint=models.CheckConstraint(
                condition=models.Q(("cantidad_prescrita__gt", 0)),
                name="ck_receta_detalle_cantidad_positiva",
            ),
        ),
    ]
