# Generated by Django 5.1.4 on 2026-07-14 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expediente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtencionOdontologia',
            fields=[
                ('atencion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='odontologia', serialize=False, to='expediente.atencion')),
                ('examen_estomatognatico', models.JSONField(blank=True, default=dict)),
                ('indices', models.JSONField(blank=True, default=dict, help_text='CPO-D, placa, periodontal')),
                ('plan_tratamiento', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'atención de odontología',
                'verbose_name_plural': 'atenciones de odontología',
            },
        ),
        migrations.CreateModel(
            name='OdontogramaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pieza_fdi', models.CharField(help_text='Notación FDI de dos dígitos', max_length=2)),
                ('superficie', models.CharField(blank=True, max_length=2)),
                ('estado_codigo', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('inicial', 'Inicial'), ('evolucion', 'Evolución')], default='inicial', max_length=10)),
                ('observacion', models.CharField(blank=True, max_length=255)),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odontograma', to='expediente.atencion')),
            ],
            options={
                'verbose_name': 'detalle de odontograma',
                'verbose_name_plural': 'detalles de odontograma',
            },
        ),
    ]
