# Generated by Django 5.1.4 on 2026-07-16 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontologia', '0002_catalogo_odontograma_procedimientos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='odontogramadetalle',
            new_name='odontologia_atencio_6b396e_idx',
            old_name='odontologia_atenc_pieza_idx',
        ),
        migrations.AddField(
            model_name='procedimiento',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedimiento',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='procedimiento',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
