# Generated by Django 5.1.4 on 2026-07-14 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expediente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedimientoEnfermeria',
            fields=[
                ('atencion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='enfermeria', serialize=False, to='expediente.atencion')),
                ('procedimientos', models.JSONField(blank=True, default=list)),
                ('inmunizaciones', models.JSONField(blank=True, default=list)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'atención de enfermería',
                'verbose_name_plural': 'atenciones de enfermería',
            },
        ),
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('fc', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='frecuencia cardíaca')),
                ('fr', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='frecuencia respiratoria')),
                ('pa_sistolica', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pa_diastolica', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sat_o2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('talla', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('imc', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('glicemia_capilar', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signos_vitales', to='expediente.atencion')),
            ],
            options={
                'verbose_name': 'signos vitales',
                'verbose_name_plural': 'signos vitales',
            },
        ),
    ]
