# Generated by Django 6.0.7 on 2026-07-14 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermeria', '0002_initial'),
        ('expediente', '0002_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtencionEnfermeria',
            fields=[
                ('atencion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='enfermeria', serialize=False, to='expediente.atencion')),
                ('procedimientos', models.JSONField(blank=True, default=list, help_text='Lista de procedimientos: [{tipo, detalle, observaciones}]')),
                ('inmunizaciones', models.JSONField(blank=True, default=list, help_text='[{vacuna, dosis, lote, laboratorio, proxima_dosis}]')),
                ('charla_educativa', models.CharField(blank=True, help_text='Tema si aplica.', max_length=200)),
                ('n_asistentes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'atención de enfermería',
                'verbose_name_plural': 'atenciones de enfermería',
            },
        ),
        migrations.RemoveField(
            model_name='procedimientoenfermeria',
            name='atencion',
        ),
        migrations.AlterModelOptions(
            name='signosvitales',
            options={'ordering': ['-fecha_hora'], 'verbose_name': 'signos vitales', 'verbose_name_plural': 'signos vitales'},
        ),
        migrations.AddField(
            model_name='signosvitales',
            name='expediente',
            field=models.ForeignKey(blank=True, help_text='Se puede rellenar por FK directa aunque no exista atención.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signos_vitales', to='expediente.expediente'),
        ),
        migrations.AddField(
            model_name='signosvitales',
            name='perimetro_abdominal',
            field=models.PositiveSmallIntegerField(blank=True, help_text='cm', null=True),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='atencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signos_vitales', to='expediente.atencion'),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='glicemia_capilar',
            field=models.PositiveSmallIntegerField(blank=True, help_text='mg/dL', null=True),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='imc',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Calculado automáticamente si hay peso y talla.', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='kg', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signos_tomados', to='usuarios.perfilprofesional'),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='sat_o2',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Saturación O2 (%)', null=True),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='talla',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='metros', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='°C', max_digits=4, null=True),
        ),
        migrations.AddIndex(
            model_name='signosvitales',
            index=models.Index(fields=['expediente', 'fecha_hora'], name='enfermeria__expedie_fc175f_idx'),
        ),
        migrations.DeleteModel(
            name='ProcedimientoEnfermeria',
        ),
    ]
