# Generated by Django 5.1.4 on 2026-09-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enfermeria", "0003_atencionenfermeria_and_more"),
        ("expediente", "0003_expediente_ck_expediente_discapacidad_hasta_100"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="signosvitales",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("temperatura__isnull", True),
                    models.Q(("temperatura__gte", 25), ("temperatura__lte", 45)),
                    _connector="OR",
                ),
                name="ck_signos_temperatura_plausible",
            ),
        ),
        migrations.AddConstraint(
            model_name="signosvitales",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("sat_o2__isnull", True), ("sat_o2__lte", 100), _connector="OR"
                ),
                name="ck_signos_saturacion_hasta_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="signosvitales",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("talla__isnull", True),
                    models.Q(("talla__gt", 0), ("talla__lte", 3)),
                    _connector="OR",
                ),
                name="ck_signos_talla_en_metros",
            ),
        ),
        migrations.AddConstraint(
            model_name="signosvitales",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("peso__isnull", True),
                    models.Q(("peso__gt", 0), ("peso__lte", 500)),
                    _connector="OR",
                ),
                name="ck_signos_peso_plausible",
            ),
        ),
        migrations.AddConstraint(
            model_name="signosvitales",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("pa_sistolica__isnull", True),
                    ("pa_diastolica__isnull", True),
                    ("pa_sistolica__gt", models.F("pa_diastolica")),
                    _connector="OR",
                ),
                name="ck_signos_sistolica_mayor_que_diastolica",
            ),
        ),
    ]
