# Generated by Django 5.1.4 on 2026-07-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FichaSocioeconomica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('vigente', models.BooleanField(default=True)),
                ('origen', models.CharField(choices=[('matricula', 'Pre-poblada desde matrícula'), ('verificada_ts', 'Verificada por Trabajo Social')], default='matricula', max_length=14)),
                ('ingresos', models.JSONField(blank=True, default=dict)),
                ('egresos', models.JSONField(blank=True, default=dict)),
                ('ingresos_totales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('egresos_totales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vivienda_estudiante', models.JSONField(blank=True, default=dict)),
                ('vivienda_familiar', models.JSONField(blank=True, default=dict)),
                ('convivencia', models.JSONField(blank=True, default=dict)),
                ('situacion_laboral', models.JSONField(blank=True, default=dict)),
                ('salud_familiar', models.JSONField(blank=True, default=dict)),
                ('puntaje', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('estrato', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name': 'ficha socioeconómica',
                'verbose_name_plural': 'fichas socioeconómicas',
            },
        ),
        migrations.CreateModel(
            name='VisitaDomiciliaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('condiciones_verificadas', models.JSONField(blank=True, default=dict)),
                ('georreferencia', models.JSONField(blank=True, default=dict)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'visita domiciliaria',
                'verbose_name_plural': 'visitas domiciliarias',
            },
        ),
    ]
