# Generated by Django 5.1.4 on 2026-07-14 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expediente', '0002_initial'),
        ('trabajo_social', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fichasocioeconomica',
            name='expediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fichas_socio', to='expediente.expediente'),
        ),
        migrations.AddField(
            model_name='visitadomiciliaria',
            name='atencion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='expediente.atencion'),
        ),
    ]
