# Generated by Django 5.1.4 on 2026-09-02 13:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expediente", "0003_expediente_ck_expediente_discapacidad_hasta_100"),
        ("trabajo_social", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fichasocioeconomica",
            options={
                "ordering": ["-version"],
                "verbose_name": "ficha socioeconómica",
                "verbose_name_plural": "fichas socioeconómicas",
            },
        ),
        migrations.AddConstraint(
            model_name="fichasocioeconomica",
            constraint=models.UniqueConstraint(
                condition=models.Q(("vigente", True)),
                fields=("expediente",),
                name="uniq_ficha_socio_vigente_por_expediente",
            ),
        ),
        migrations.AddConstraint(
            model_name="fichasocioeconomica",
            constraint=models.UniqueConstraint(
                fields=("expediente", "version"),
                name="uniq_ficha_socio_version_por_expediente",
            ),
        ),
        migrations.AddConstraint(
            model_name="fichasocioeconomica",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("egresos_totales__gte", 0), ("ingresos_totales__gte", 0)
                ),
                name="ck_ficha_socio_totales_no_negativos",
            ),
        ),
    ]
