# Generated by Django 5.1.4 on 2026-07-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('rol_activo', models.CharField(blank=True, max_length=20)),
                ('accion', models.CharField(choices=[('create', 'Crear'), ('read', 'Leer'), ('update', 'Actualizar'), ('soft_delete', 'Eliminar (lógico)'), ('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('export', 'Exportar'), ('print', 'Imprimir'), ('break_glass', 'Acceso de emergencia')], max_length=14)),
                ('modulo', models.CharField(blank=True, max_length=40)),
                ('entidad', models.CharField(blank=True, max_length=60)),
                ('entidad_id', models.CharField(blank=True, max_length=40)),
                ('expediente_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('resultado', models.CharField(default='ok', max_length=20)),
            ],
            options={
                'verbose_name': 'registro de auditoría',
                'verbose_name_plural': 'registros de auditoría',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
