# Generated by Django 5.1.4 on 2026-07-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logauditoria',
            name='accion',
            field=models.CharField(choices=[('create', 'Crear'), ('read', 'Leer'), ('update', 'Actualizar'), ('soft_delete', 'Eliminar (lógico)'), ('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('export', 'Exportar'), ('print', 'Imprimir'), ('break_glass', 'Acceso de emergencia'), ('sign_request', 'Solicitar firma'), ('sign', 'Firmar documento')], max_length=14),
        ),
    ]
