# Generated by Django 5.1.4 on 2026-09-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0003_alter_logauditoria_accion"),
    ]

    operations = [
        migrations.AddField(
            model_name="logauditoria",
            name="servicio",
            field=models.CharField(blank=True, db_index=True, max_length=60),
        ),
    ]
